site_name: OneFlow_User_Op
dev_addr: '127.0.0.1:5500' #默认值

theme:
  name: "material"
  favicon: https://github.com/ultralytics/assets/raw/main/logo/favicon-yolo.ico
  font:
    text: Roboto

  palette:
    # Palette toggle for light mode
    - scheme: default
      # primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      # primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - instant
    - content.action.edit
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.expand
    - content.tabs.link  # all code tabs change simultaneously



extra_css:
  - style.css 


markdown_extensions:
  # Div text decorators
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - def_list
  # Syntax highlight
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Button
  - attr_list

  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # Highlight
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - mkdocstrings
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Primary navigation
nav:
  - Home: index.md 
  - 工具篇: 
    - 前言: utils.md
    - Visual Studio Code: utils/vscode.md
    - VS Code 插件::clangd: utils/clangd.md
    - VS Code 插件::Python: utils/Python.md
    - VS Code 插件::Live Server: utils/live_server.md
    - Debug工具::pdb: utils/pdb.md
    - Debug工具::GDB: utils/gdb.md
    - 性能工具::nsys: utils/nsys.md
  - 开发篇:
    - 如何在 OneFlow 中新增算子: OneFlow/forward.md
    - OneFlow CUDA Elementwise: OneFlow/OneFlow_CUDA_Elementwise.md
    - 反向传播实现示例: OneFlow/backward.md
    - PyTorch:
      - Ox01: PyTorch/Ox01.md

  - 测试篇:
    - Test: OneFlow/test.md
  - 文档篇:
    - Document: OneFlow/document.md


